gen:
	../../Darser/darser -i sdl.yaml \
	-a source/dud/sdlang2/ast.d -b "dud.sdlang2" \
	-p source/dud/sdlang2/parser.d -q "dud.sdlang2" \
	-e source/dud/sdlang2/exception.d -g "dud.sdlang2" \
	-v source/dud/sdlang2/visitor.d -w "dud.sdlang2" \
	-t /dev/null -r "dud.sdlang2" \
	-u "dud.sdlang2" -s "dud.sdlang2" \
	--safe --pure
