gen:
	../../Darser/darser -i sdl.yaml \
	-a source/dud/sdlang/ast.d -b "dud.sdlang" \
	-p source/dud/sdlang/parser.d -q "dud.sdlang" \
	-e source/dud/sdlang/exception.d -g "dud.sdlang" \
	-v source/dud/sdlang/visitor.d -w "dud.sdlang" \
	-t /dev/null -r "dud.sdlang" \
	-u "dud.sdlang" -s "dud.sdlang" \
	--safe --pure
