gentestdata:
	../../dubproxy/dubproxy -m true -n allcodedlangpackages.json
	../../dubproxy/dubproxy -a true -i allcodedlangpackages.json -u true --verbose --genAllTags true \
		--overrideTree yes -o ../testpackages -f ../testpackages
